export const REQUEST_ALL_POSTS = "REQUEST_ALL_POSTS";
export const RECEIVE_ALL_POSTS = "RECEIVE_POSTS";
export const ADD_POST = "ADD_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const VOTE_POST = "VOTE_POST";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const VOTE_COMMENT = "VOTE_COMMENT";

export const FILTER_POSTS_BY_TITLE = "FILTER_POSTS_BY_TITLE";
export const FILTER_POSTS_SCORE = "FILTER_POSTS_SCORE";
export const FILTER_POSTS_DATE = "FILTER_POSTS_DATE";
